// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

package msgs

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type PublicKey struct {
	N                []byte `protobuf:"bytes,1,opt" json:"N,omitempty"`
	E                *int64 `protobuf:"varint,2,opt" json:"E,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PublicKey) Reset()         { *m = PublicKey{} }
func (m *PublicKey) String() string { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()    {}

func (m *PublicKey) GetN() []byte {
	if m != nil {
		return m.N
	}
	return nil
}

func (m *PublicKey) GetE() int64 {
	if m != nil && m.E != nil {
		return *m.E
	}
	return 0
}

type PrivateKey struct {
	PublicKey        *PublicKey `protobuf:"bytes,1,opt,name=publicKey" json:"publicKey,omitempty"`
	D                []byte     `protobuf:"bytes,2,opt" json:"D,omitempty"`
	Primes           [][]byte   `protobuf:"bytes,3,rep,name=primes" json:"primes,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *PrivateKey) Reset()         { *m = PrivateKey{} }
func (m *PrivateKey) String() string { return proto.CompactTextString(m) }
func (*PrivateKey) ProtoMessage()    {}

func (m *PrivateKey) GetPublicKey() *PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *PrivateKey) GetD() []byte {
	if m != nil {
		return m.D
	}
	return nil
}

func (m *PrivateKey) GetPrimes() [][]byte {
	if m != nil {
		return m.Primes
	}
	return nil
}

type SignatureRequest struct {
	VoterPublicKey   *PublicKey `protobuf:"bytes,1,opt,name=voterPublicKey" json:"voterPublicKey,omitempty"`
	BlindedBallot    []byte     `protobuf:"bytes,2,opt,name=blindedBallot" json:"blindedBallot,omitempty"`
	VoterSignature   []byte     `protobuf:"bytes,3,opt,name=voterSignature" json:"voterSignature,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *SignatureRequest) Reset()         { *m = SignatureRequest{} }
func (m *SignatureRequest) String() string { return proto.CompactTextString(m) }
func (*SignatureRequest) ProtoMessage()    {}

func (m *SignatureRequest) GetVoterPublicKey() *PublicKey {
	if m != nil {
		return m.VoterPublicKey
	}
	return nil
}

func (m *SignatureRequest) GetBlindedBallot() []byte {
	if m != nil {
		return m.BlindedBallot
	}
	return nil
}

func (m *SignatureRequest) GetVoterSignature() []byte {
	if m != nil {
		return m.VoterSignature
	}
	return nil
}

type SignatureResponse struct {
	Request                *SignatureRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	BlindedBallotSignature []byte            `protobuf:"bytes,2,opt,name=blindedBallotSignature" json:"blindedBallotSignature,omitempty"`
	XXX_unrecognized       []byte            `json:"-"`
}

func (m *SignatureResponse) Reset()         { *m = SignatureResponse{} }
func (m *SignatureResponse) String() string { return proto.CompactTextString(m) }
func (*SignatureResponse) ProtoMessage()    {}

func (m *SignatureResponse) GetRequest() *SignatureRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *SignatureResponse) GetBlindedBallotSignature() []byte {
	if m != nil {
		return m.BlindedBallotSignature
	}
	return nil
}

type Vote struct {
	Ballot           []byte `protobuf:"bytes,1,opt,name=ballot" json:"ballot,omitempty"`
	BallotSignature  []byte `protobuf:"bytes,2,opt,name=ballotSignature" json:"ballotSignature,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}

func (m *Vote) GetBallot() []byte {
	if m != nil {
		return m.Ballot
	}
	return nil
}

func (m *Vote) GetBallotSignature() []byte {
	if m != nil {
		return m.BallotSignature
	}
	return nil
}

type BallotEntry struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Ballot           []byte  `protobuf:"bytes,2,opt,name=ballot" json:"ballot,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BallotEntry) Reset()         { *m = BallotEntry{} }
func (m *BallotEntry) String() string { return proto.CompactTextString(m) }
func (*BallotEntry) ProtoMessage()    {}

func (m *BallotEntry) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *BallotEntry) GetBallot() []byte {
	if m != nil {
		return m.Ballot
	}
	return nil
}

type VoteResponse struct {
	BallotEntry          []byte `protobuf:"bytes,1,opt,name=ballotEntry" json:"ballotEntry,omitempty"`
	BallotEntrySignature []byte `protobuf:"bytes,2,opt,name=ballotEntrySignature" json:"ballotEntrySignature,omitempty"`
	XXX_unrecognized     []byte `json:"-"`
}

func (m *VoteResponse) Reset()         { *m = VoteResponse{} }
func (m *VoteResponse) String() string { return proto.CompactTextString(m) }
func (*VoteResponse) ProtoMessage()    {}

func (m *VoteResponse) GetBallotEntry() []byte {
	if m != nil {
		return m.BallotEntry
	}
	return nil
}

func (m *VoteResponse) GetBallotEntrySignature() []byte {
	if m != nil {
		return m.BallotEntrySignature
	}
	return nil
}

func init() {
}
